version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./api:/usr/src/api
    depends_on:
      - db

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: db
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/mysql-store:/var/lib/mysql
      - ./mysql/mysql-logs:/var/log/mysql
